version: "3.7"
services:
  web:
    image: web:v1
    container_name: web
    build:
      context: ./web
    volumes:
      - ./web/app:/app/app
      - ./web/components:/app/components
      - ./web/lib:/app/lib
      - ./web/public:/app/public
    ports:
      - "3000:3000"
  api:
    image: api:v1
    container_name: api
    build:
      context: ./api
    volumes:
      - ./api:/app
    command: uvicorn run:server --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env.api
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:16.1-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - ./db/.env.db
