export const Employees = [
    {
      id: 1,
      firstName: "Igor",
      lastName: "Talkov",
      gender: "Male",
      age: 45,
      email: "igortalkiv@hotmail.com",
      phone: "063823234",
      education: "PhD",
      occupation: "Musician",
      experienceYears: 32,
      salary: 10321,
      maritalStatus: "Married",
      numberOfChildren: 1,
    },
    {
      id: 2,
      firstName: "Alla",
      lastName: "Pugachiova",
      gender: "Female",
      age: 58,
      email: "allapugachiova@gmail.com",
      phone: "063823234",
      education: "Bachelor",
      occupation: "Singer",
      experienceYears: 32,
      salary: 9321,
      maritalStatus: "Married",
      numberOfChildren: 3,
    },
    {
      id: 3,
      firstName: "Iurii",
      lastName: "Shatunov",
      gender: "Male",
      age: 34,
      email: "iuriishatunov@mail.ru",
      phone: "063823234",
      education: "PhD",
      occupation: "Hacker",
      experienceYears: 18,
      salary: 8321,
      maritalStatus: "Married",
      numberOfChildren: 2,
    },
  
    {
      id: 4,
      firstName: "Bogdan",
      lastName: "Titamir",
      gender: "Male",
      age: 54,
      email: "bogdantitamir@gmail.com",
      phone: "063343234",
      education: "High School",
      occupation: "Construction Worker",
      experienceYears: 34,
      salary: 4321,
      maritalStatus: "Single",
      numberOfChildren: 0,
    },
    {
      id: 5,
      firstName: "Sofia",
      lastName: "Rotaru",
      gender: "Female",
      age: 34,
      email: "sofiarotaru@hotmail.com",
      phone: "063823234",
      education: "Bachelor",
      occupation: "Singer",
      experienceYears: 14,
      salary: 4321,
      maritalStatus: "Divorced",
      numberOfChildren: 2,
    },
  ]
  